#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Agile_SalesApp.Resource", IsApplication=true)]

namespace Agile_SalesApp
{
	
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7F010000
			public const int background = 2130771968;
			
			// aapt resource value: 0x7F010001
			public const int colorAccent = 2130771969;
			
			// aapt resource value: 0x7F010002
			public const int colorAccentDark = 2130771970;
			
			// aapt resource value: 0x7F010003
			public const int colorAccentLight = 2130771971;
			
			// aapt resource value: 0x7F010004
			public const int colorOnPrimary = 2130771972;
			
			// aapt resource value: 0x7F010005
			public const int colorPrimary = 2130771973;
			
			// aapt resource value: 0x7F010006
			public const int colorPrimaryDark = 2130771974;
			
			// aapt resource value: 0x7F010007
			public const int colorRed = 2130771975;
			
			// aapt resource value: 0x7F010008
			public const int colorRipple = 2130771976;
			
			// aapt resource value: 0x7F010009
			public const int ic_launcher_background = 2130771977;
			
			// aapt resource value: 0x7F01000A
			public const int white = 2130771978;
			
			// aapt resource value: 0x7F01000B
			public const int white_2 = 2130771979;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7F020000
			public const int button_gradient_1 = 2130837504;
			
			// aapt resource value: 0x7F020001
			public const int button_gradient_2 = 2130837505;
			
			// aapt resource value: 0x7F020002
			public const int button_selector = 2130837506;
			
			// aapt resource value: 0x7F020003
			public const int sale_sharks = 2130837507;
			
			// aapt resource value: 0x7F020004
			public const int splash_layout = 2130837508;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7F030000
			public const int btn1 = 2130903040;
			
			// aapt resource value: 0x7F030001
			public const int btn2 = 2130903041;
			
			// aapt resource value: 0x7F030002
			public const int btn3 = 2130903042;
			
			// aapt resource value: 0x7F030003
			public const int btn4 = 2130903043;
			
			// aapt resource value: 0x7F030004
			public const int btn5 = 2130903044;
			
			// aapt resource value: 0x7F030005
			public const int etID = 2130903045;
			
			// aapt resource value: 0x7F030006
			public const int etName = 2130903046;
			
			// aapt resource value: 0x7F030007
			public const int etPrice = 2130903047;
			
			// aapt resource value: 0x7F030008
			public const int etQuantity = 2130903048;
			
			// aapt resource value: 0x7F030009
			public const int listCategory = 2130903049;
			
			// aapt resource value: 0x7F03000A
			public const int listProduct = 2130903050;
			
			// aapt resource value: 0x7F03000B
			public const int listSale = 2130903051;
			
			// aapt resource value: 0x7F03000C
			public const int spinnerCategory = 2130903052;
			
			// aapt resource value: 0x7F03000D
			public const int spinnerProduct = 2130903053;
			
			// aapt resource value: 0x7F03000E
			public const int text1 = 2130903054;
			
			// aapt resource value: 0x7F03000F
			public const int text2 = 2130903055;
			
			// aapt resource value: 0x7F030010
			public const int text3 = 2130903056;
			
			// aapt resource value: 0x7F030011
			public const int text4 = 2130903057;
			
			// aapt resource value: 0x7F030012
			public const int text5 = 2130903058;
			
			// aapt resource value: 0x7F030013
			public const int textCategory = 2130903059;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7F040000
			public const int activity_main = 2130968576;
			
			// aapt resource value: 0x7F040001
			public const int add_category_main = 2130968577;
			
			// aapt resource value: 0x7F040002
			public const int add_product_main = 2130968578;
			
			// aapt resource value: 0x7F040003
			public const int add_sale_main = 2130968579;
			
			// aapt resource value: 0x7F040004
			public const int category_main = 2130968580;
			
			// aapt resource value: 0x7F040005
			public const int category_row = 2130968581;
			
			// aapt resource value: 0x7F040006
			public const int delete_category_main = 2130968582;
			
			// aapt resource value: 0x7F040007
			public const int delete_product_main = 2130968583;
			
			// aapt resource value: 0x7F040008
			public const int delete_sale_main = 2130968584;
			
			// aapt resource value: 0x7F040009
			public const int edit_category_main = 2130968585;
			
			// aapt resource value: 0x7F04000A
			public const int edit_product_main = 2130968586;
			
			// aapt resource value: 0x7F04000B
			public const int product_main = 2130968587;
			
			// aapt resource value: 0x7F04000C
			public const int product_row = 2130968588;
			
			// aapt resource value: 0x7F04000D
			public const int sale_main = 2130968589;
			
			// aapt resource value: 0x7F04000E
			public const int sale_row = 2130968590;
			
			// aapt resource value: 0x7F04000F
			public const int view_category_main = 2130968591;
			
			// aapt resource value: 0x7F040010
			public const int view_product_main = 2130968592;
			
			// aapt resource value: 0x7F040011
			public const int view_sale_main = 2130968593;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7F050000
			public const int ic_launcher = 2131034112;
			
			// aapt resource value: 0x7F050001
			public const int ic_launcher_foreground = 2131034113;
			
			// aapt resource value: 0x7F050002
			public const int ic_launcher_round = 2131034114;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7F060000
			public const int action_settings = 2131099648;
			
			// aapt resource value: 0x7F060001
			public const int app_name = 2131099649;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7F070000
			public const int AppTheme = 2131165184;
			
			// aapt resource value: 0x7F070001
			public const int BlueButton = 2131165185;
			
			// aapt resource value: 0x7F070002
			public const int MyTheme = 2131165186;
			
			// aapt resource value: 0x7F070003
			public const int MyTheme_Base = 2131165187;
			
			// aapt resource value: 0x7F070004
			public const int MyTheme_Splash = 2131165188;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
